import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';
import eslintConfigPrettier from 'eslint-config-prettier';
import eslintPluginPrettier from 'eslint-plugin-prettier/recommended';
import globals from 'globals';

export default tseslint.config(
  // Global ignores
  {
    ignores: [
      'dist/',
      'node_modules/',
      '*.js',
      '!eslint.config.js',
      'scripts/',
      // Generated by scripts/bundle-dashboard.cjs – edit src/web/ui/ instead
      'src/web/dashboard.ts',
      // Browser-side UI sources: not part of the TypeScript program, so the
      // type-aware config cannot parse them.
      'src/web/ui/**',
    ],
  },

  // Base ESLint recommended rules
  eslint.configs.recommended,

  // TypeScript recommended rules
  ...tseslint.configs.recommended,

  // Project-specific TypeScript settings
  {
    languageOptions: {
      globals: {
        ...globals.node,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Relax rules that conflict with the codebase style
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-non-null-assertion': 'off',

      // Allow empty catch blocks (common in HA error handling)
      'no-empty': ['error', { allowEmptyCatch: true }],

      // Prefer const
      'prefer-const': 'warn',

      // No console (use logger)
      'no-console': 'warn',
    },
  },

  // Prettier integration (must be last)
  eslintConfigPrettier,
  eslintPluginPrettier,
);
